const initialCardsArray = [
  ['Action (Set A)', 'Action (Set B)', 'Action (Set C)', 'Adjective', 'Animal (Set A)', 'Animal (Set B)', 'Clothes', 'Emotion'],
  [
    {
      word: 'cry',
      translation: 'плакать',
      image: 'assets/images/cry.jpg',
      audioSrc: 'assets/audio/cry.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'dance',
      translation: 'танцевать',
      image: 'assets/images/dance.jpg',
      audioSrc: 'assets/audio/dance.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'dive',
      translation: 'нырять',
      image: 'assets/images/dive.jpg',
      audioSrc: 'assets/audio/dive.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'draw',
      translation: 'рисовать',
      image: 'assets/images/draw.jpg',
      audioSrc: 'assets/audio/draw.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'fish',
      translation: 'ловить рыбу',
      image: 'assets/images/fish.jpg',
      audioSrc: 'assets/audio/fish.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'fly',
      translation: 'летать',
      image: 'assets/images/fly.jpg',
      audioSrc: 'assets/audio/fly.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'hug',
      translation: 'обнимать',
      image: 'assets/images/hug.jpg',
      audioSrc: 'assets/audio/hug.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'jump',
      translation: 'прыгать',
      image: 'assets/images/jump.jpg',
      audioSrc: 'assets/audio/jump.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
  ],
  [
    {
      word: 'open',
      translation: 'открывать',
      image: 'assets/images/open.jpg',
      audioSrc: 'assets/audio/open.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'play',
      translation: 'играть',
      image: 'assets/images/play.jpg',
      audioSrc: 'assets/audio/play.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'point',
      translation: 'указывать',
      image: 'assets/images/point.jpg',
      audioSrc: 'assets/audio/point.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'ride',
      translation: 'ездить',
      image: 'assets/images/ride.jpg',
      audioSrc: 'assets/audio/ride.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'run',
      translation: 'бегать',
      image: 'assets/images/run.jpg',
      audioSrc: 'assets/audio/run.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'sing',
      translation: 'петь',
      image: 'assets/images/sing.jpg',
      audioSrc: 'assets/audio/sing.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'skip',
      translation: 'пропускать, прыгать',
      image: 'assets/images/skip.jpg',
      audioSrc: 'assets/audio/skip.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'swim',
      translation: 'плавать',
      image: 'assets/images/swim.jpg',
      audioSrc: 'assets/audio/swim.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
  ],
  [
    {
      word: 'argue',
      translation: 'спорить',
      image: 'assets/images/argue.jpg',
      audioSrc: 'assets/audio/argue.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'build',
      translation: 'строить',
      image: 'assets/images/build.jpg',
      audioSrc: 'assets/audio/build.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'carry',
      translation: 'нести',
      image: 'assets/images/carry.jpg',
      audioSrc: 'assets/audio/carry.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'catch',
      translation: 'ловить',
      image: 'assets/images/catch.jpg',
      audioSrc: 'assets/audio/catch.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'drive',
      translation: 'водить машину',
      image: 'assets/images/drive.jpg',
      audioSrc: 'assets/audio/drive.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'drop',
      translation: 'падать',
      image: 'assets/images/drop.jpg',
      audioSrc: 'assets/audio/drop.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'pull',
      translation: 'тащить',
      image: 'assets/images/pull.jpg',
      audioSrc: 'assets/audio/pull.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'push',
      translation: 'толкать',
      image: 'assets/images/push.jpg',
      audioSrc: 'assets/audio/push.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
  ],
  [
    {
      word: 'big',
      translation: 'большой',
      image: 'assets/images/big.jpg',
      audioSrc: 'assets/audio/big.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'small',
      translation: 'маленький',
      image: 'assets/images/small.jpg',
      audioSrc: 'assets/audio/small.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'fast',
      translation: 'быстрый',
      image: 'assets/images/fast.jpg',
      audioSrc: 'assets/audio/fast.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'slow',
      translation: 'медленный',
      image: 'assets/images/slow.jpg',
      audioSrc: 'assets/audio/slow.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'friendly',
      translation: 'дружелюбный',
      image: 'assets/images/friendly.jpg',
      audioSrc: 'assets/audio/friendly.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'unfriendly',
      translation: 'недружелюбный',
      image: 'assets/images/unfriendly.jpg',
      audioSrc: 'assets/audio/unfriendly.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'young',
      translation: 'молодой',
      image: 'assets/images/young.jpg',
      audioSrc: 'assets/audio/young.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'old',
      translation: 'старый',
      image: 'assets/images/old.jpg',
      audioSrc: 'assets/audio/old.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
  ],
  [
    {
      word: 'cat',
      translation: 'кот',
      image: 'assets/images/cat.jpg',
      audioSrc: 'assets/audio/cat.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'chick',
      translation: 'цыплёнок',
      image: 'assets/images/chick.jpg',
      audioSrc: 'assets/audio/chick.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'chicken',
      translation: 'курица',
      image: 'assets/images/chicken.jpg',
      audioSrc: 'assets/audio/chicken.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'dog',
      translation: 'собака',
      image: 'assets/images/dog.jpg',
      audioSrc: 'assets/audio/dog.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'horse',
      translation: 'лошадь',
      image: 'assets/images/horse.jpg',
      audioSrc: 'assets/audio/horse.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'pig',
      translation: 'свинья',
      image: 'assets/images/pig.jpg',
      audioSrc: 'assets/audio/pig.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'rabbit',
      translation: 'кролик',
      image: 'assets/images/rabbit.jpg',
      audioSrc: 'assets/audio/rabbit.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'sheep',
      translation: 'овца',
      image: 'assets/images/sheep.jpg',
      audioSrc: 'assets/audio/sheep.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
  ],
  [
    {
      word: 'bird',
      translation: 'птица',
      image: 'assets/images/bird.jpg',
      audioSrc: 'assets/audio/bird.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'fish',
      translation: 'рыба',
      image: 'assets/images/fish1.jpg',
      audioSrc: 'assets/audio/fish.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'frog',
      translation: 'жаба',
      image: 'assets/images/frog.jpg',
      audioSrc: 'assets/audio/frog.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'giraffe',
      translation: 'жирафа',
      image: 'assets/images/giraffe.jpg',
      audioSrc: 'assets/audio/giraffe.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'lion',
      translation: 'лев',
      image: 'assets/images/lion.jpg',
      audioSrc: 'assets/audio/lion.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'mouse',
      translation: 'мышь',
      image: 'assets/images/mouse.jpg',
      audioSrc: 'assets/audio/mouse.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'turtle',
      translation: 'черепаха',
      image: 'assets/images/turtle.jpg',
      audioSrc: 'assets/audio/turtle.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'dolphin',
      translation: 'дельфин',
      image: 'assets/images/dolphin.jpg',
      audioSrc: 'assets/audio/dolphin.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
  ],
  [
    {
      word: 'skirt',
      translation: 'юбка',
      image: 'assets/images/skirt.jpg',
      audioSrc: 'assets/audio/skirt.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'pants',
      translation: 'брюки',
      image: 'assets/images/pants.jpg',
      audioSrc: 'assets/audio/pants.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'blouse',
      translation: 'блузка',
      image: 'assets/images/blouse.jpg',
      audioSrc: 'assets/audio/blouse.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'dress',
      translation: 'платье',
      image: 'assets/images/dress.jpg',
      audioSrc: 'assets/audio/dress.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'boot',
      translation: 'ботинок',
      image: 'assets/images/boot.jpg',
      audioSrc: 'assets/audio/boot.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'shirt',
      translation: 'рубашка',
      image: 'assets/images/shirt.jpg',
      audioSrc: 'assets/audio/shirt.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'coat',
      translation: 'пальто',
      image: 'assets/images/coat.jpg',
      audioSrc: 'assets/audio/coat.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'shoe',
      translation: 'туфли',
      image: 'assets/images/shoe.jpg',
      audioSrc: 'assets/audio/shoe.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
  ],
  [
    {
      word: 'sad',
      translation: 'грустный',
      image: 'assets/images/sad.jpg',
      audioSrc: 'assets/audio/sad.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'angry',
      translation: 'сердитый',
      image: 'assets/images/angry.jpg',
      audioSrc: 'assets/audio/angry.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'happy',
      translation: 'счастливый',
      image: 'assets/images/happy.jpg',
      audioSrc: 'assets/audio/happy.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'tired',
      translation: 'уставший',
      image: 'assets/images/tired.jpg',
      audioSrc: 'assets/audio/tired.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'surprised',
      translation: 'удивлённый',
      image: 'assets/images/surprised.jpg',
      audioSrc: 'assets/audio/surprised.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'scared',
      translation: 'испуганный',
      image: 'assets/images/scared.jpg',
      audioSrc: 'assets/audio/scared.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'smile',
      translation: 'улыбка',
      image: 'assets/images/smile.jpg',
      audioSrc: 'assets/audio/smile.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
    {
      word: 'laugh',
      translation: 'смех',
      image: 'assets/images/laugh.jpg',
      audioSrc: 'assets/audio/laugh.mp3',
      trainClicks: 0,
      successPlayClicks: 0,
      failPlayClicks: 0,
    },
  ],
];

let cards = JSON.parse(localStorage.getItem('cardsArray')) || initialCardsArray;

//cards = JSON.parse(localStorage.getItem('cardsArray'));

export { initialCardsArray, cards };
